# Generated by Django 5.0.6 on 2024-05-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_movies',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='watched_movies',
            field=models.ManyToManyField(blank=True, related_name='watched_by', through='movies.WatchedMovie', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='in_watchlists', to='movies.movie'),
        ),
    ]
